name = "cf-lumine"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
routes = [
  { pattern = "lol.luminecf.my.id", custom_domain = true },
  { pattern = "support.zoom.us.lol.luminecf.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.lol.luminecf.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.lol.luminecf.my.id", custom_domain = true },
  { pattern = "zoomgov.lol.luminecf.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.lol.luminecf.my.id", custom_domain = true },
  { pattern = "z-p15.www.instagram.com.lol.luminecf.my.id", custom_domain = true },
  { pattern = "investors.spotify.com.lol.luminecf.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.lol.luminecf.my.id", custom_domain = true }
]


[vars]
PROXYIP = "103.133.223.51:2096,103.149.165.47:443,103.6.207.108:8080,206.189.129.187:443,143.244.130.180:443,172.232.239.151:587,3.109.185.221:443,103.168.146.169:20132,165.232.182.81:443,43.204.80.35:443,147.139.245.56:443,103.97.88.133:443,35.200.202.118:443,146.190.111.165:443"
UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
